IE.fModule({
  f: function (exports, require, module, global) {
    'use strict';
    Object.defineProperty(exports, '__esModule', { value: true });
    exports.StylesCouleurs = void 0;
    require('Couleurs.css');
    exports.StylesCouleurs = {
      FondBlanc: 'FondBlanc',
      Blanc: 'Blanc',
      Noir: 'Noir',
      bgRedFoncee: 'bg-red-foncee',
      colorRedFoncee: 'color-red-foncee',
      texteRedFoncee: 'texte-red-foncee',
      bgRedMoyen: 'bg-red-moyen',
      colorRedMoyen: 'color-red-moyen',
      texteRedMoyen: 'texte-red-moyen',
      bgRedClaire: 'bg-red-claire',
      colorRedClaire: 'color-red-claire',
      texteRedClaire: 'texte-red-claire',
      bgGreenFoncee: 'bg-green-foncee',
      colorGreenFoncee: 'color-green-foncee',
      texteGreenFoncee: 'texte-green-foncee',
      bgGreenMoyen: 'bg-green-moyen',
      colorGreenMoyen: 'color-green-moyen',
      texteGreenMoyen: 'texte-green-moyen',
      bgGreenClaire: 'bg-green-claire',
      colorGreenClaire: 'color-green-claire',
      texteGreenClaire: 'texte-green-claire',
      bgOrangeFoncee: 'bg-orange-foncee',
      colorOrangeFoncee: 'color-orange-foncee',
      texteOrangeFoncee: 'texte-orange-foncee',
      bgOrangeMoyen: 'bg-orange-moyen',
      colorOrangeMoyen: 'color-orange-moyen',
      texteOrangeMoyen: 'texte-orange-moyen',
      bgOrangeClaire: 'bg-orange-claire',
      colorOrangeClaire: 'color-orange-claire',
      texteOrangeClaire: 'texte-orange-claire',
      bgBlueFoncee: 'bg-blue-foncee',
      colorBlueFoncee: 'color-blue-foncee',
      texteBlueFoncee: 'texte-blue-foncee',
      bgBlueMoyen: 'bg-blue-moyen',
      colorBlueMoyen: 'color-blue-moyen',
      texteBlueMoyen: 'texte-blue-moyen',
      bgBlueClaire: 'bg-blue-claire',
      colorBlueClaire: 'color-blue-claire',
      texteBlueClaire: 'texte-blue-claire',
      bgNeutreLight: 'bg-neutre-light',
      colorNeutreLight: 'color-neutre-light',
      bgNeutreLegere: 'bg-neutre-legere',
      colorNeutreLegere: 'color-neutre-legere',
      bgNeutreLegere2: 'bg-neutre-legere2',
      colorNeutreLegere2: 'color-neutre-legere2',
      bgNeutreClaire: 'bg-neutre-claire',
      colorNeutreClaire: 'color-neutre-claire',
      bgNeutreMoyen1: 'bg-neutre-moyen1',
      colorNeutreMoyen1: 'color-neutre-moyen1',
      bgNeutreMoyen2: 'bg-neutre-moyen2',
      colorNeutreMoyen2: 'color-neutre-moyen2',
      bgNeutreMoyen3: 'bg-neutre-moyen3',
      colorNeutreMoyen3: 'color-neutre-moyen3',
      bgNeutreFoncee: 'bg-neutre-foncee',
      colorNeutreFoncee: 'color-neutre-foncee',
      bgNeutreSombre: 'bg-neutre-sombre',
      colorNeutreSombre: 'color-neutre-sombre',
    };
  },
  fn: 'couleurs.css.js',
});