IE.fModule({
  f: function (exports, require, module, global) {
    'use strict';
    Object.defineProperty(exports, '__esModule', { value: true });
    exports.StylesImageSco = void 0;
    require('ImageSco.css');
    exports.StylesImageSco = {
      image_centrale_notification: 'image_centrale_notification',
      Image_CommandeKiosque: 'Image_CommandeKiosque',
      Image_CoursExportPNCoursRouge: 'Image_CoursExportPNCoursRouge',
      Image_CoursExportPNCoursOrange: 'Image_CoursExportPNCoursOrange',
      Image_SystemeReserverSalle: 'Image_SystemeReserverSalle',
      Image_SystemeReserverMateriel: 'Image_SystemeReserverMateriel',
      Image_SystemeAlerte: 'Image_SystemeAlerte',
      Image_NotificationAlerte: 'Image_NotificationAlerte',
      Image_Ajout1Etat: 'Image_Ajout1Etat',
      Image_TAF_Public: 'Image_TAF_Public',
      Image_TAF_Duree: 'Image_TAF_Duree',
      Image_Trombone: 'Image_Trombone',
      Image_Publie: 'Image_Publie',
      Image_NonPublie: 'Image_NonPublie',
      Image_PublieEnAttente: 'Image_PublieEnAttente',
      Image_Publie_Grise: 'Image_Publie_Grise',
      Image_NonPublie_Grise: 'Image_NonPublie_Grise',
      Image_Verrou: 'Image_Verrou',
      Image_VerrouFait: 'Image_VerrouFait',
      Image_TAF_Niveau: 'Image_TAF_Niveau',
      Image_Crayon1EtatClair: 'Image_Crayon1EtatClair',
      Image_EvaluationTresInsatisfait: 'Image_EvaluationTresInsatisfait',
      Image_EvaluationInsatisfait: 'Image_EvaluationInsatisfait',
      Image_EvaluationSatisfait: 'Image_EvaluationSatisfait',
      Image_EvaluationTresSatisfait: 'Image_EvaluationTresSatisfait',
      Image_EvaluationTresInsatisfaitListe:
        'Image_EvaluationTresInsatisfaitListe',
      Image_EvaluationInsatisfaitListe: 'Image_EvaluationInsatisfaitListe',
      Image_EvaluationSatisfaitListe: 'Image_EvaluationSatisfaitListe',
      Image_EvaluationTresSatisfaitListe: 'Image_EvaluationTresSatisfaitListe',
      Image_Punition_RealiseNon: 'Image_Punition_RealiseNon',
      Image_Punition_RealiseOuNon: 'Image_Punition_RealiseOuNon',
      Image_Punition_Realise: 'Image_Punition_Realise',
      Image_Punition_RealiseProgramme: 'Image_Punition_RealiseProgramme',
      Image_CDT_Editeurs: 'Image_CDT_Editeurs',
      Image_Casier: 'Image_Casier',
      Image_Logo_BriefMe: 'Image_Logo_BriefMe',
      Image_Logo_BriefMe_AvecGranularite: 'Image_Logo_BriefMe_AvecGranularite',
      Image_Logo_Generation5: 'Image_Logo_Generation5',
      Image_Logo_Generation5_AvecGranularite:
        'Image_Logo_Generation5_AvecGranularite',
      Image_Logo_Universalis: 'Image_Logo_Universalis',
      Image_Logo_Universalis_AvecGranularite:
        'Image_Logo_Universalis_AvecGranularite',
      Image_Logo_EDUCLEVER: 'Image_Logo_EDUCLEVER',
      Image_Logo_EDUCLEVER_AvecGranularite:
        'Image_Logo_EDUCLEVER_AvecGranularite',
      Image_Logo_EDULIB: 'Image_Logo_EDULIB',
      Image_Logo_EDULIB_AvecGranularite: 'Image_Logo_EDULIB_AvecGranularite',
      Image_Logo_LIVRESCOLAIRE: 'Image_Logo_LIVRESCOLAIRE',
      Image_Logo_LIVRESCOLAIRE_AvecGranularite:
        'Image_Logo_LIVRESCOLAIRE_AvecGranularite',
      Image_Logo_EDUCARTE: 'Image_Logo_EDUCARTE',
      Image_Logo_EDUCARTE_AvecGranularite:
        'Image_Logo_EDUCARTE_AvecGranularite',
      Image_Logo_BBM: 'Image_Logo_BBM',
      Image_Logo_BBM_AvecGranularite: 'Image_Logo_BBM_AvecGranularite',
      Image_Logo_PearlTrees: 'Image_Logo_PearlTrees',
      Image_Logo_PearlTrees_AvecGranularite:
        'Image_Logo_PearlTrees_AvecGranularite',
      Image_Logo_PopLab: 'Image_Logo_PopLab',
      Image_Logo_PopLab_AvecGranularite: 'Image_Logo_PopLab_AvecGranularite',
      Image_Logo_MadMagz_AvecGranularite: 'Image_Logo_MadMagz_AvecGranularite',
      Image_Logo_MadMagz: 'Image_Logo_MadMagz',
      Image_Logo_Sondo_AvecGranularite: 'Image_Logo_Sondo_AvecGranularite',
      Image_Logo_Sondo: 'Image_Logo_Sondo',
      Image_Logo_ShortEdition_AvecGranularite:
        'Image_Logo_ShortEdition_AvecGranularite',
      Image_Logo_ShortEdition: 'Image_Logo_ShortEdition',
      Image_Logo_Wiloki: 'Image_Logo_Wiloki',
      Image_Logo_Wiloki_AvecGranularite: 'Image_Logo_Wiloki_AvecGranularite',
      Image_Logo_EDUMEDIA: 'Image_Logo_EDUMEDIA',
      Image_Logo_EDUMEDIA_AvecGranularite:
        'Image_Logo_EDUMEDIA_AvecGranularite',
      Image_AppelNonFait: 'Image_AppelNonFait',
      Image_AppelVerrouFait: 'Image_AppelVerrouFait',
      Image_AppelVerrouNonFait: 'Image_AppelVerrouNonFait',
      Image_CahierDeTexte6Etats: 'Image_CahierDeTexte6Etats',
      Image_CahierDeTexte_Verrouille6Etats:
        'Image_CahierDeTexte_Verrouille6Etats',
      Image_CahierDeTexte: 'Image_CahierDeTexte',
      Image_CahierDeTexte_Verrouille: 'Image_CahierDeTexte_Verrouille',
      Image_ListeCommentaire: 'Image_ListeCommentaire',
      Image_DonneesMembre: 'Image_DonneesMembre',
      Image_IconeMoins: 'Image_IconeMoins',
      Image_IconePlus: 'Image_IconePlus',
      Image_IconeEvaluation: 'Image_IconeEvaluation',
      Image_IconeAP: 'Image_IconeAP',
      Image_IconeEPI: 'Image_IconeEPI',
      Image_CoursVirtuelCDT: 'Image_CoursVirtuelCDT',
      Image_ColonneTransportScolaire: 'Image_ColonneTransportScolaire',
      Image_CoursExportSTSNonExportable: 'Image_CoursExportSTSNonExportable',
      Image_STSPartiellementExportable: 'Image_STSPartiellementExportable',
      Image_CoursExportExportableConditions:
        'Image_CoursExportExportableConditions',
      Image_CoursExportSTSExportable: 'Image_CoursExportSTSExportable',
      Image_Attention: 'Image_Attention',
      Image_MessagerieRepondre: 'Image_MessagerieRepondre',
      Image_CommandeRecherche: 'Image_CommandeRecherche',
      Image_SigmaAbsence: 'Image_SigmaAbsence',
      Image_SigmaRetard: 'Image_SigmaRetard',
      Image_OrdonnerElmtProgrammes: 'Image_OrdonnerElmtProgrammes',
      Image_OptionOrdonnerPourListe: 'Image_OptionOrdonnerPourListe',
      Image_DiagAffEleTGris: 'Image_DiagAffEleTGris',
      asIcon: 'as-icon',
      Image_DiagAbsClasse: 'Image_DiagAbsClasse',
      Image_DiagStageEleve: 'Image_DiagStageEleve',
      Image_DiagEleveExclu: 'Image_DiagEleveExclu',
      Image_PointBleuEnRelief: 'Image_PointBleuEnRelief',
      Image_PointGrisEnRelief: 'Image_PointGrisEnRelief',
      Image_TravailDonnePourCours: 'Image_TravailDonnePourCours',
      Image_SaisieCompetenceDevoir: 'Image_SaisieCompetenceDevoir',
      Image_BtnPDF: 'Image_BtnPDF',
      Image_Realise: 'Image_Realise',
      Image_RealiseNon: 'Image_RealiseNon',
      Image_RealiseProgramme: 'Image_RealiseProgramme',
      Image_RealiseOuNon: 'Image_RealiseOuNon',
      Image_IconePunition: 'Image_IconePunition',
      Image_CreationCompteCloudIndex: 'Image_CreationCompteCloudIndex',
      Image_AssociationCompteCloudIndex: 'Image_AssociationCompteCloudIndex',
      Image_AlerteMiseAJourPRN: 'Image_AlerteMiseAJourPRN',
      Image_AlerteMiseAJourPRM: 'Image_AlerteMiseAJourPRM',
      Image_CoursPrevus: 'Image_CoursPrevus',
      Image_StickerALaMaison: 'Image_StickerALaMaison',
      Image_Partenaire_Canope: 'Image_Partenaire_Canope',
      Image_Partenaire_Canope_2022: 'Image_Partenaire_Canope_2022',
      Image_DiodeVerte: 'Image_DiodeVerte',
      Image_DiodeGrise: 'Image_DiodeGrise',
    };
  },
  fn: 'imagesco.css.js',
});