IE.fModule({
  f: function (exports, require, module, global) {
    'use strict';
    Object.defineProperty(exports, '__esModule', { value: true });
    exports.StylesObjetDonneesListeFlatDesign = void 0;
    require('ObjetDonneesListeFlatDesign.css');
    exports.StylesObjetDonneesListeFlatDesign = {
      ObjetListe: 'ObjetListe',
      skin_flatDesign: 'skin_flatDesign',
      fdDesignMinimal: 'fd-design-minimal',
      indentationFils1: 'indentation-fils-1',
      indentationFils2: 'indentation-fils-2',
      indentationFils3: 'indentation-fils-3',
      indentationFils4: 'indentation-fils-4',
      ombreDroite: 'ombre-droite',
      ombreScroll: 'ombre-scroll',
      top: 'top',
      bottom: 'bottom',
      enteteOmbree: 'entete-ombree',
      fd_ligne: 'fd_ligne',
      fdPerefilsFusion: 'fd-perefils-fusion',
      withSelect: 'with-select',
      selected: 'selected',
      btnImage: 'btnImage',
      btnImageIcon: 'btnImageIcon',
      colorNeutre: 'color-neutre',
      btnImageDisable: 'btnImageDisable',
      btActivable: 'bt-activable',
      liste_contenu_ligne: 'liste_contenu_ligne',
      zoneMessageLarge: 'zone-message-large',
      zoneDeploiement: 'zone-deploiement',
      btnDeploiement: 'btn-deploiement',
      zoneGauche: 'zone-gauche',
      iecb: 'iecb',
      agenda: 'agenda',
      traitCouleur: 'trait-couleur',
      zoneCentrale: 'zone-centrale',
      zoneContenuFormat: 'zone-contenu-format',
      alignCenter: 'align-center',
      icon: 'icon',
      zonePrincipale: 'zone-principale',
      titrePrincipal: 'titre-principal',
      infosSupp: 'infos-supp',
      ieSousTitre: 'ie-sous-titre',
      ieChips: 'ie-chips',
      text: 'text',
      noEllipsis: 'no-ellipsis',
      zoneComplementaire: 'zone-complementaire',
      time: 'time',
      compteur: 'compteur',
      btnConteneur: 'btn-conteneur',
      infoDuree: 'info-duree',
      iconesConteneur: 'icones-conteneur',
      carreIcone: 'carre-icone',
      tiny: 'tiny',
      bloc4: 'bloc-4',
      bloc6: 'bloc-6',
      long: 'long',
      zoneMessage: 'zone-message',
      likeLink: 'like-link',
      colorThemeFoncee: 'color-theme-foncee',
      alertColor: 'alert-color',
      off: 'off',
      zoneDroite: 'zone-droite',
      btnSurvol: 'btn-survol',
      liste_celluleGrid: 'liste_celluleGrid',
      fd_intertitre: 'fd_intertitre',
      fdIntertitreIndent: 'fd-intertitre-indent',
      liste_sepligne: 'liste_sepligne',
      fdStyleIntertitre: 'fd-style-intertitre',
      h3: 'h3',
      h4: 'h4',
      h5: 'h5',
      collection: 'collection',
      collectionItem: 'collection-item',
      liste_btnentete: 'liste_btnentete',
      listeTotaleFd: 'liste-totale-fd',
      listeHeader: 'liste-header',
      listeFooter: 'liste-footer',
      listeHeaderFooterInScroll: 'listeHeaderFooterInScroll',
      footer: 'footer',
      selectable: 'selectable',
      totalEtiquSep: 'total-etiqu-sep',
      aSavoirMessage: 'a-savoir-message',
      totalEtiqu: 'total-etiqu',
      totalContent: 'total-content',
    };
  },
  fn: 'objetdonneeslisteflatdesign.css.js',
});