IE.fModule({
  f: function (exports, require, module, global) {
    'use strict';
    Object.defineProperty(exports, '__esModule', { value: true });
    exports.SUtilitairePagePubliqueEtablissement = void 0;
    require('./UtilitairePagePubliqueEtablissement.scss');
    exports.SUtilitairePagePubliqueEtablissement = {
      utilPagePubliqueEtab: 'utilPagePubliqueEtab',
      tpl3cols: 'tpl-3cols',
      bandeauHaut: 'bandeauHaut',
      avecSeparateur: 'avecSeparateur',
      identiteEtab: 'identiteEtab',
      accesEspaces: 'accesEspaces',
      ObjetSaisie: 'ObjetSaisie',
      Combo: 'Combo',
      asInput: 'as-input',
      ocb_cont: 'ocb_cont',
      ocb_bouton: 'ocb_bouton',
      asPlaceholder: 'as-placeholder',
      nomApp: 'nomApp',
      deroulantConteneurShowHide: 'deroulant-conteneur-show-hide',
      listeAsOptions: 'liste-as-options',
      active: 'active',
      centered: 'centered',
      banniere: 'banniere',
      imgParDefaut: 'imgParDefaut',
      imgParDefautPrimaire: 'imgParDefautPrimaire',
      textBanniere: 'text-banniere',
      liensFavoris: 'liensFavoris',
      EspaceMobileIndex: 'EspaceMobileIndex',
      corps: 'corps',
      widget: 'widget',
      EspaceIndex: 'EspaceIndex',
      accueilWidgetContent: 'accueil-widget-content',
      filtreConteneur: 'filtre-conteneur',
      contentContainer: 'content-container',
      listeClickable: 'liste-clickable',
      listeImbriquee: 'liste-imbriquee',
      blocDateConteneur: 'bloc-date-conteneur',
      asInfo: 'as-info',
      btnCollapse: 'btn-collapse',
      edito: 'edito',
      menudelacantine: 'menudelacantine',
      underline: 'underline',
      zonePrincipale: 'zonePrincipale',
      zoneAside: 'zoneAside',
      zoneFooter: 'zoneFooter',
      noZoneAside: 'no-zone-aside',
      noZonePrincipale: 'no-zone-principale',
      cookiesDisclaimer: 'cookies-disclaimer',
      asLink: 'as-link',
      ieBouton: 'ieBouton',
      liensFooter: 'liensFooter',
      estVide: 'est-vide',
      liensInfosEtab: 'liensInfosEtab',
      liensReseauxSoc: 'liensReseauxSoc',
      lien: 'lien',
      copyright: 'copyright',
      hostFranceContainer: 'host-france-container',
      logoIndexContain: 'logo-index-contain',
      logoIndexInverse: 'logo-index-inverse',
      hostText: 'host-text',
      certif27001: 'certif-27001',
      tplMarge: 'tpl-marge',
      tplMain: 'tpl-main',
      fluidMobile: 'fluid-mobile',
      agenda: 'agenda',
      actualites: 'actualites',
      wrap: 'wrap',
      titre: 'titre',
      iecb: 'iecb',
    };
  },
  fn: 'utilitairepagepubliqueetablissement.css.js',
});