IE.fModule({
  f: function (exports, require, module, global) {
    'use strict';
    Object.defineProperty(exports, '__esModule', { value: true });
    exports.StylesFormComponents = void 0;
    require('Form-components.css');
    exports.StylesFormComponents = {
      styleInput: 'style-input',
      asInput: 'as-input',
      asPlaceholder: 'as-placeholder',
      listAsMenu: 'list-as-menu',
      labelForInput: 'label-for-input',
      ObjetAffichagePageAvecMenusDeroulants_divPrimaire:
        'ObjetAffichagePageAvecMenusDeroulants_divPrimaire',
      PetitEspaceDroit: 'PetitEspaceDroit',
      comboGlobalWrapper: 'combo-global-wrapper',
      asPassword: 'as-password',
      asSearch: 'as-search',
      disabled: 'disabled',
      ObjetCelluleDate: 'ObjetCelluleDate',
      inputWrapper: 'input-wrapper',
      inputWrapperDisabled: 'input-wrapper-disabled',
      btnImageDisable: 'btnImageDisable',
      btnImage: 'btnImage',
      icon: 'icon',
      icon_angle_left: 'icon_angle_left',
      ocb_cont: 'ocb_cont',
      ocbLibelle: 'ocb-libelle',
      ocb_bouton: 'ocb_bouton',
      ocb_icone_gauche: 'ocb_icone_gauche',
      asSelect: 'as-select',
      onMobile: 'on-mobile',
      asMultiChoix: 'as-multi-choix',
      asDatePicker: 'as-date-picker',
      deroulantConteneurShowHide: 'deroulant-conteneur-show-hide',
      listeAsOptions: 'liste-as-options',
      elementDistinct: 'element-distinct',
      titreListe: 'titre-liste',
      asLi: 'as-li',
      listeFondCumul: 'liste-fond-cumul',
      elementIndentation: 'element-indentation',
      selected: 'selected',
      text_empty: 'text_empty',
      dmi_texte_combo: 'dmi_texte_combo',
      iconic: 'iconic',
      multiSelections: 'multi-selections',
      checkConteneur: 'check-conteneur',
      isTactile: 'is-tactile',
      validateConteneur: 'validate-conteneur',
      likeInput: 'like-input',
      isTiny: 'is-tiny',
      tox: 'tox',
      toxTinymce: 'tox-tinymce',
      browserDefault: 'browser-default',
      textareamaxWrapper: 'textareamax-wrapper',
      notHover: 'not-hover',
      realSize: 'real-size',
      avecChips: 'avec-chips',
      asColorPicker: 'as-color-picker',
      ieChips: 'ie-chips',
      themePicker: 'theme-picker',
      carreColor: 'carre-color',
      hasScroll: 'has-scroll',
      objetInterfaceMobile_zoneSelection: 'objetInterfaceMobile_zoneSelection',
      ObjetFenetre_Date_racine: 'ObjetFenetre_Date_racine',
      widget: 'widget',
      btnAvecEdition: 'btn-avec-edition',
      avecPrevsuiv: 'avec-prevsuiv',
      zoneContenu: 'zone-contenu',
      ObjetSaisie: 'ObjetSaisie',
      ieCombo: 'ie-combo',
      ObjetSaisie_cont: 'ObjetSaisie_cont',
      saisieCdtSelection: 'saisie-cdt-selection',
      btnPrevSuiv: 'btn-prev-suiv',
      ieBtnselecteur: 'ie-btnselecteur',
      comboSelecteur: 'combo-selecteur',
      asSelecteur: 'as-selecteur',
    };
  },
  fn: 'form-components.css.js',
});