IE.fModule({
  f: function (exports, require, module, global) {
    'use strict';
    Object.defineProperty(exports, '__esModule', { value: true });
    exports.SImageSco = void 0;
    require('./ImageSco.scss');
    exports.SImageSco = {
      Image_CoursExportPNCoursRouge: 'Image_CoursExportPNCoursRouge',
      Image_CoursExportPNCoursOrange: 'Image_CoursExportPNCoursOrange',
      Image_TAF_Public: 'Image_TAF_Public',
      Image_Publie: 'Image_Publie',
      Image_NonPublie: 'Image_NonPublie',
      Image_PublieEnAttente: 'Image_PublieEnAttente',
      Image_Publie_Grise: 'Image_Publie_Grise',
      Image_NonPublie_Grise: 'Image_NonPublie_Grise',
      Image_Verrou: 'Image_Verrou',
      Image_VerrouFait: 'Image_VerrouFait',
      Image_EvaluationTresInsatisfait: 'Image_EvaluationTresInsatisfait',
      Image_EvaluationInsatisfait: 'Image_EvaluationInsatisfait',
      Image_EvaluationSatisfait: 'Image_EvaluationSatisfait',
      Image_EvaluationTresSatisfait: 'Image_EvaluationTresSatisfait',
      Image_EvaluationTresInsatisfaitListe:
        'Image_EvaluationTresInsatisfaitListe',
      Image_EvaluationInsatisfaitListe: 'Image_EvaluationInsatisfaitListe',
      Image_EvaluationSatisfaitListe: 'Image_EvaluationSatisfaitListe',
      Image_EvaluationTresSatisfaitListe: 'Image_EvaluationTresSatisfaitListe',
      Image_Punition_RealiseNon: 'Image_Punition_RealiseNon',
      Image_Punition_RealiseOuNon: 'Image_Punition_RealiseOuNon',
      Image_Punition_Realise: 'Image_Punition_Realise',
      Image_Punition_RealiseProgramme: 'Image_Punition_RealiseProgramme',
      Image_CDT_Editeurs: 'Image_CDT_Editeurs',
      Image_Casier: 'Image_Casier',
      Image_CahierDeTexte6Etats: 'Image_CahierDeTexte6Etats',
      Image_CahierDeTexte: 'Image_CahierDeTexte',
      Image_ListeCommentaire: 'Image_ListeCommentaire',
      Image_DonneesMembre: 'Image_DonneesMembre',
      Image_IconeMoins: 'Image_IconeMoins',
      Image_IconePlus: 'Image_IconePlus',
      Image_IconeEvaluation: 'Image_IconeEvaluation',
      Image_IconeAP: 'Image_IconeAP',
      Image_IconeEPI: 'Image_IconeEPI',
      Image_CoursVirtuelCDT: 'Image_CoursVirtuelCDT',
      Image_ColonneTransportScolaire: 'Image_ColonneTransportScolaire',
      Image_CoursExportSTSNonExportable: 'Image_CoursExportSTSNonExportable',
      Image_STSPartiellementExportable: 'Image_STSPartiellementExportable',
      Image_CoursExportExportableConditions:
        'Image_CoursExportExportableConditions',
      Image_CoursExportSTSExportable: 'Image_CoursExportSTSExportable',
      Image_Attention: 'Image_Attention',
      Image_MessagerieRepondre: 'Image_MessagerieRepondre',
      Image_CommandeRecherche: 'Image_CommandeRecherche',
      Image_SigmaAbsence: 'Image_SigmaAbsence',
      Image_SigmaRetard: 'Image_SigmaRetard',
      Image_OrdonnerElmtProgrammes: 'Image_OrdonnerElmtProgrammes',
      Image_DiagAbsClasse: 'Image_DiagAbsClasse',
      Image_DiagStageEleve: 'Image_DiagStageEleve',
      Image_DiagEleveExclu: 'Image_DiagEleveExclu',
      Image_PointBleuEnRelief: 'Image_PointBleuEnRelief',
      Image_TravailDonnePourCours: 'Image_TravailDonnePourCours',
      Image_SaisieCompetenceDevoir: 'Image_SaisieCompetenceDevoir',
      Image_BtnPDF: 'Image_BtnPDF',
      Image_Realise: 'Image_Realise',
      Image_RealiseNon: 'Image_RealiseNon',
      Image_RealiseProgramme: 'Image_RealiseProgramme',
      Image_RealiseOuNon: 'Image_RealiseOuNon',
      Image_IconePunition: 'Image_IconePunition',
      Image_CreationCompteCloudIndex: 'Image_CreationCompteCloudIndex',
      Image_AssociationCompteCloudIndex: 'Image_AssociationCompteCloudIndex',
      Image_AlerteMiseAJourPRN: 'Image_AlerteMiseAJourPRN',
      Image_AlerteMiseAJourPRM: 'Image_AlerteMiseAJourPRM',
      Image_StickerALaMaison: 'Image_StickerALaMaison',
      Image_Partenaire_Canope: 'Image_Partenaire_Canope',
      Image_Partenaire_Canope_2022: 'Image_Partenaire_Canope_2022',
      Image_DiodeVerte: 'Image_DiodeVerte',
      Image_DiodeGrise: 'Image_DiodeGrise',
      Image_AccesRestreint: 'Image_AccesRestreint',
      Image_DestinataireCourrier: 'Image_DestinataireCourrier',
      Image_AbsenceOuverte: 'Image_AbsenceOuverte',
      Image_AbsenceFermee: 'Image_AbsenceFermee',
      Image_Dll_VerrouPetit: 'Image_Dll_VerrouPetit',
      Image_VisaEtablissement: 'Image_VisaEtablissement',
      Image_VisaInspecteur: 'Image_VisaInspecteur',
      Image_DeploiementBandeau: 'Image_DeploiementBandeau',
      Image_PaletteDesCouleurs: 'Image_PaletteDesCouleurs',
      Image_Bas: 'Image_Bas',
      Image_DossierComportement_Ferme: 'Image_DossierComportement_Ferme',
      Hachure: 'Hachure',
    };
  },
  fn: 'imagesco.css.js',
});