IE.fModule({
  f: function (exports, require, module, global) {
    'use strict';
    Object.defineProperty(exports, '__esModule', { value: true });
    exports.SIEHtmlBouton = void 0;
    require('./IEHtml.Bouton.scss');
    exports.SIEHtmlBouton = {
      ieBouton: 'ieBouton',
      boutonCarre: 'bouton-carre',
      ieBoutonIcon: 'ieBoutonIcon',
      EspaceIndex: 'EspaceIndex',
      ieBoutonDefautSansImage: 'ieBoutonDefautSansImage',
      themeBoutonPrimaire: 'themeBoutonPrimaire',
      ThemeMobileHP: 'ThemeMobileHP',
      ThemePronoteCampus: 'ThemePronoteCampus',
      ThemeProduitHP: 'ThemeProduitHP',
      ThemeCorail: 'ThemeCorail',
      hyperplanning: 'hyperplanning',
      ieRipple: 'ie-ripple',
      themeBoutonNeutre: 'themeBoutonNeutre',
      iconeSvg: 'icone-svg',
      heightAuto: 'height-auto',
      fixedMobile: 'fixed-mobile',
      smallBt: 'small-bt',
      hasDots: 'has-dots',
      themeTabBar: 'themeTabBar',
      sideIcon: 'side-icon',
      btnSmall: 'btn-small',
      btnFlatMinimal: 'btn-flat-minimal',
      ieBtnContImgImg: 'ieBtnContImg-img',
      themeHyperplanning: 'theme-hyperplanning',
      themeEdt: 'theme-edt',
      themePronote: 'theme-pronote',
      ThemeNeutre: 'ThemeNeutre',
      widget: 'widget',
      ctaConteneur: 'cta-conteneur',
      bgWhite: 'bg-white',
      isInfo: 'is-info',
      isSuccess: 'is-success',
      isError: 'is-error',
      isAlert: 'is-alert',
      darkMode: 'dark-mode',
      EspaceMobileIndex: 'EspaceMobileIndex',
      ieBtnContImgTexte: 'ieBtnContImg-texte',
      smallMobile: 'small-mobile',
      btn: 'btn',
      btnFlat: 'btn-flat',
      tab: 'tab',
      iconeBadge: 'icone-badge',
      btnImageDisable: 'btnImageDisable',
    };
  },
  fn: 'iehtml.bouton.css.js',
});