IE.fModule({
  f: function (exports, require, module, global) {
    'use strict';
    Object.defineProperty(exports, '__esModule', { value: true });
    exports.SObjetVisuEleveQCM = void 0;
    require('./ObjetVisuEleveQCM.scss');
    exports.SObjetVisuEleveQCM = {
      EspaceIndex: 'EspaceIndex',
      wrapperQuestionQCM: 'wrapperQuestionQCM',
      cbr: 'cbr',
      cbrVisu: 'cbr-visu',
      cbrCorrige: 'cbr-corrige',
      qcmViewer: 'qcm-viewer',
      ObjetFenetreChoixAssociation_racine:
        'ObjetFenetreChoixAssociation_racine',
      darkMode: 'dark-mode',
      forQcm: 'for-qcm',
      libText: 'lib-text',
      cbrCoche: 'cbr-coche',
      misEnForme: 'mis-en-forme',
      EspaceMobileIndex: 'EspaceMobileIndex',
      libelle: 'libelle',
      thumbnail: 'thumbnail',
      isKo: 'is-ko',
      qcmResultat: 'qcm-resultat',
      isChecked: 'is-checked',
      iconResult: 'icon-result',
      isOk: 'is-ok',
      cbrGroup: 'cbr-group',
      qcmComment: 'qcm-comment',
      maReponse: 'ma-reponse',
      zoneReponse: 'zone-reponse',
      spellBlock: 'spell-block',
      reponseInput: 'reponse-input',
      spellContain: 'spell-contain',
      isNumeric: 'is-numeric',
      isNone: 'is-none',
      fieldsWrapper: 'fields-wrapper',
      inputWrap: 'input-wrap',
      associationWrapper: 'association-wrapper',
      assoItem: 'asso-item',
      btAssoContain: 'bt-asso-contain',
      choixWrapper: 'choix-wrapper',
      reponse: 'reponse',
      asso: 'asso',
      withImg: 'with-img',
      corrige: 'corrige',
      rappelReponse: 'rappel-reponse',
      listeReponses: 'liste-reponses',
      reponseItem: 'reponse-item',
      elementContainer: 'element-container',
      groupBtn: 'group-btn',
      prev: 'prev',
      primary: 'primary',
      next: 'next',
      chronoView: 'chrono-view',
      timelineNav: 'timeline-nav',
      timelineBtn: 'timeline-btn',
      noQuestion: 'no-question',
      isDisabled: 'is-disabled',
      isDone: 'is-done',
      isMedium: 'is-medium',
      isCurrent: 'is-current',
      globalContain: 'global-contain',
      mainContain: 'main-contain',
      content: 'content',
      compteur: 'compteur',
      questNum: 'quest-num',
      nbrPoint: 'nbr-point',
      contenuQuestion: 'contenu-question',
      wrapperEnonceQuestionQCM: 'wrapperEnonceQuestionQCM',
      browserDefault: 'browser-default',
      mediaContain: 'media-contain',
      PageModalite: 'PageModalite',
      PageConsignes: 'PageConsignes',
      consigneWrapper: 'consigne-wrapper',
      PagePresentationCorrige: 'PagePresentationCorrige',
      important: 'important',
      competences: 'competences',
      titre: 'titre',
      recapWrapper: 'recap-wrapper',
      PageRessenti: 'PageRessenti',
      messageWrapper: 'message-wrapper',
      PageRecapitulatif: 'PageRecapitulatif',
      PageFinQCM: 'PageFinQCM',
      PageQCMNonDemarre: 'PageQCMNonDemarre',
      PageCloture: 'PageCloture',
      PageMessageErreur: 'PageMessageErreur',
      iecb: 'iecb',
      asChips: 'as-chips',
      PageCorrigeComplet: 'PageCorrigeComplet',
      PageCorrigeQuestion: 'PageCorrigeQuestion',
      corrigeWrapper: 'corrige-wrapper',
      libelleComplementaireScore: 'libelle-complementaire-score',
      reponseOk: 'reponse-ok',
      reponsePartielle: 'reponse-partielle',
      score: 'score',
      separateur: 'separateur',
      zoneMessage: 'zone-message',
      question: 'question',
      hintWrapper: 'hint-wrapper',
      libellesContain: 'libelles-contain',
      ico: 'ico',
      iconContain: 'icon-contain',
      enonce: 'enonce',
      inputsCorrige: 'inputs-corrige',
      legendeCloze: 'legende-cloze',
      pastille: 'pastille',
      exacte: 'exacte',
      partielle: 'partielle',
      fausse: 'fausse',
    };
  },
  fn: 'objetvisueleveqcm.css.js',
});