IE.fModule({
  f: function (exports, require, module, global) {
    'use strict';
    Object.defineProperty(exports, '__esModule', { value: true });
    exports.StylesPages_connexion = void 0;
    require('pages_connexion.css');
    exports.StylesPages_connexion = {
      ImageFond: 'ImageFond',
      BottomLeft: 'BottomLeft',
      Repeat: 'Repeat',
      Cover: 'Cover',
      Image_Connexion_Fond: 'Image_Connexion_Fond',
      Icone_EspaceEnseignant: 'Icone_EspaceEnseignant',
      Icone_EspacePrimEnseignant: 'Icone_EspacePrimEnseignant',
      Icone_EspaceAdministratif: 'Icone_EspaceAdministratif',
      Icone_EspacePrimAdministratif: 'Icone_EspacePrimAdministratif',
      Icone_EspaceEtudiant: 'Icone_EspaceEtudiant',
      Icone_EspacePrimEtudiant: 'Icone_EspacePrimEtudiant',
      Icone_EspaceSecretariat: 'Icone_EspaceSecretariat',
      Icone_EspaceParent: 'Icone_EspaceParent',
      Icone_EspacePrimParent: 'Icone_EspacePrimParent',
      Icone_EspaceAcademie: 'Icone_EspaceAcademie',
      Icone_EspaceEntreprise: 'Icone_EspaceEntreprise',
      Icone_EspaceAccompagnant: 'Icone_EspaceAccompagnant',
      Icone_EspacePrimAccompagnant: 'Icone_EspacePrimAccompagnant',
      Icone_EspaceAppariteur: 'Icone_EspaceAppariteur',
      Icone_EspaceTuteur: 'Icone_EspaceTuteur',
      Icone_EspacePeriscolaire: 'Icone_EspacePeriscolaire',
      Icone_EspaceMairie: 'Icone_EspaceMairie',
      Icone_EspaceInscription: 'Icone_EspaceInscription',
      Icone_EspacePrimInscription: 'Icone_EspacePrimInscription',
      Icone_EspaceInvite: 'Icone_EspaceInvite',
      Icone_EspaceAdministrationConsole: 'Icone_EspaceAdministrationConsole',
      btnConnexion: 'btn-connexion',
      imgBtnBg: 'img-btn-bg',
      imgBtn: 'img-btn',
      libelle: 'libelle',
      listeWrapper: 'liste-wrapper',
      retourEspace: 'retour-espace',
      titreDescriptif: 'titre-descriptif',
      mainWrapper: 'main-wrapper',
      wrapperConnectConteneur: 'wrapper-connect-conteneur',
      choixProfilContain: 'choix-profil-contain',
      iccp_lienDesktop: 'iccp_lienDesktop',
      libelleContain: 'libelle-contain',
      avecDescriptif: 'avec-descriptif',
      btnWrapper: 'btn-wrapper',
      descriptif: 'descriptif',
      imageAside: 'image-aside',
      blocElem: 'bloc-elem',
      footer: 'footer',
      blocConnexionWrapper: 'bloc-connexion-wrapper',
      loginBox: 'loginBox',
      connexionWrapper: 'connexion-wrapper',
      formWrapper: 'form-wrapper',
      inputField: 'input-field',
      recupMdp: 'recup-mdp',
      messageErreur: 'message-erreur',
      imgContain: 'img-contain',
      fieldsContain: 'fields-contain',
      asInput: 'as-input',
      asPassword: 'as-password',
      btnImage: 'btnImage',
      labelUp: 'label-up',
      imgInscription: 'img-inscription',
      pageDeconnexion: 'page-deconnexion',
      decoContent: 'deco-content',
      decoTitrePronote: 'deco-titre-pronote',
      decoTitrePrimaire: 'deco-titre-primaire',
      decoTitreEdt: 'deco-titre-edt',
      decoTitreHyperplanning: 'deco-titre-hyperplanning',
      pageDeconnexion_titre: 'pageDeconnexion_titre',
      message: 'message',
      bgEspaceEdt: 'bg-espace-edt',
      bgEspacePronote: 'bg-espace-pronote',
      bgEspacePrimaire: 'bg-espace-primaire',
    };
  },
  fn: 'pages_connexion.css.js',
});