IE.fModule({
  f: function (exports, require, module, global) {
    'use strict';
    Object.defineProperty(exports, '__esModule', { value: true });
    exports.StylesObjetFenetre_Espace = void 0;
    require('ObjetFenetre_Espace.css');
    exports.StylesObjetFenetre_Espace = {
      Fenetre: 'Fenetre',
      Fenetre_Bouton: 'Fenetre_Bouton',
      Fenetre_Contenu: 'Fenetre_Contenu',
      Fenetre_Titre: 'Fenetre_Titre',
      Fenetre_Espace: 'Fenetre_Espace',
      Fenetre_Cadre: 'Fenetre_Cadre',
      Fenetre_Bordure: 'Fenetre_Bordure',
      Fenetre_Impression: 'Fenetre_Impression',
      Fenetre_ImageFond: 'Fenetre_ImageFond',
      Fenetre_SeparateurVertical: 'Fenetre_SeparateurVertical',
      ZoneDeplacementFenetre: 'ZoneDeplacementFenetre',
      ObjetFenetre_Espace: 'ObjetFenetre_Espace',
      ombreCadre: 'ombre-cadre',
      sansBandeau: 'sans-bandeau',
      ctaConteneur: 'cta-conteneur',
      btnImage: 'btnImage',
      btnImageIcon: 'btnImageIcon',
      asButton: 'as-button',
      Fenetre_Scroll: 'Fenetre_Scroll',
      overflowYScroll: 'overflow-y-scroll',
      SansPaddingLR: 'SansPaddingLR',
      bandeauHeader: 'bandeau-header',
      content: 'content',
      zoneBas: 'zone-bas',
      zoneBasGauche: 'zone-bas-gauche',
      btnConteneur: 'btn-conteneur',
      contentWrapper: 'content-wrapper',
      combosWrapper: 'combos-wrapper',
      fenetreResize: 'fenetre-resize',
      left: 'left',
      right: 'right',
      top: 'top',
      bottom: 'bottom',
      coin: 'coin',
      overlayResize: 'overlay-resize',
      lockedContain: 'locked-contain',
      topLine: 'top-line',
      titreBloc: 'titre-bloc',
      listeCompetences: 'liste-competences',
      publicTeam: 'public-team',
      iecb: 'iecb',
      tinyWrapper: 'tiny-wrapper',
      btnContain: 'btn-contain',
      tinyContenu: 'tiny-contenu',
      listePj: 'liste-pj',
      generalConteneur: 'general-conteneur',
      fondGris: 'fond-gris',
      ObjetFenetre_groupeInfos: 'ObjetFenetre_groupe-infos',
      ObjetFenetre_blocInfos: 'ObjetFenetre_bloc-infos',
      fluid: 'fluid',
      fixed: 'fixed',
      inputIconised: 'input-iconised',
      icon: 'icon',
      textareamaxWrapper: 'textareamax-wrapper',
      textareaStyle: 'textarea-style',
      textareaCounter: 'textarea-counter',
      ObjetFenetre_EditionScolarite_racine:
        'ObjetFenetre_EditionScolarite_racine',
      menuTabsWrapper: 'menu-tabs-wrapper',
      listeClasses: 'liste-classes',
      listeBoutons: 'liste-boutons',
      mbXl: 'mb-xl',
      ObjetFichePopupConversation_racine: 'ObjetFichePopupConversation_racine',
      multitabsWrapper: 'multitabs-wrapper',
      destinatairesWrapper: 'destinataires-wrapper',
      menuWrapper: 'menu-wrapper',
      contenu: 'contenu',
      panel: 'panel',
      item: 'item',
      itemsWrapper: 'items-wrapper',
      radioContain: 'radio-contain',
      entites: 'entites',
      users: 'users',
      destinataireIndividuel: 'destinataire-individuel',
    };
  },
  fn: 'objetfenetre_espace.css.js',
});