IE.fModule({
  f: function (exports, require, module, global) {
    'use strict';
    Object.defineProperty(exports, '__esModule', { value: true });
    exports.SObjetFenetre_Espace = void 0;
    require('./ObjetFenetre_Espace.scss');
    exports.SObjetFenetre_Espace = {
      Fenetre: 'Fenetre',
      Fenetre_Contenu: 'Fenetre_Contenu',
      Fenetre_Titre: 'Fenetre_Titre',
      Fenetre_Espace: 'Fenetre_Espace',
      Fenetre_Cadre: 'Fenetre_Cadre',
      Fenetre_Bordure: 'Fenetre_Bordure',
      Fenetre_Impression: 'Fenetre_Impression',
      ZoneDeplacementFenetre: 'ZoneDeplacementFenetre',
      ObjetFenetre_Espace: 'ObjetFenetre_Espace',
      isAlert: 'is-alert',
      isInfo: 'is-info',
      isSuccess: 'is-success',
      ombreCadre: 'ombre-cadre',
      sansBandeau: 'sans-bandeau',
      ctaConteneur: 'cta-conteneur',
      btnImage: 'btnImage',
      btnImageIcon: 'btnImageIcon',
      asButton: 'as-button',
      Fenetre_Scroll: 'Fenetre_Scroll',
      overflowYScroll: 'overflow-y-scroll',
      SansPaddingLR: 'SansPaddingLR',
      bandeauHeader: 'bandeau-header',
      content: 'content',
      zoneBas: 'zone-bas',
      zoneBasGauche: 'zone-bas-gauche',
      btnConteneur: 'btn-conteneur',
      contentWrapper: 'content-wrapper',
      combosWrapper: 'combos-wrapper',
      fenetreResize: 'fenetre-resize',
      left: 'left',
      right: 'right',
      top: 'top',
      bottom: 'bottom',
      coin: 'coin',
      overlayResize: 'overlay-resize',
      lockedContain: 'locked-contain',
      topLine: 'top-line',
      titreBloc: 'titre-bloc',
      listeCompetences: 'liste-competences',
      publicTeam: 'public-team',
      iecb: 'iecb',
      tinyWrapper: 'tiny-wrapper',
      btnContain: 'btn-contain',
      tinyContenu: 'tiny-contenu',
      listePj: 'liste-pj',
      generalConteneur: 'general-conteneur',
      fondGris: 'fond-gris',
      ObjetFichePopupConversation_racine: 'ObjetFichePopupConversation_racine',
      multitabsWrapper: 'multitabs-wrapper',
      destinatairesWrapper: 'destinataires-wrapper',
      menuWrapper: 'menu-wrapper',
    };
  },
  fn: 'objetfenetre_espace.css.js',
});