IE.fModule({
  f: function (exports, require, module, global) {
    'use strict';
    Object.defineProperty(exports, '__esModule', { value: true });
    exports.TradGlossaireListe = void 0;
    const ObjetTraduction_1 = require('@cp/script/ObjetTraduction');
    const TradGlossaireListe = ObjetTraduction_1.TraductionsModule.getModule(
      'GlossaireListe',
      {
        doublon: '',
        doublonNom: '',
        creationImpossible: '',
        editionImpossible: '',
        suppressionImpossible: '',
        suppressionMotifImpossible: '',
        suppressionSelection: '',
        erreurDate: '',
        erreurHeureMinute: '',
        tailleMaxSaisie: '',
        creer: '',
        modifier: '',
        supprimer: '',
        nouveau: '',
        tri: '',
        toutCocher: '',
        toutDecocher: '',
        total: '',
        DossierObligatoire: '',
        HintBoutonDeploiement: '',
        DeployerLigne: '',
        ReduireLigne: '',
        HintBoutonMonter: '',
        HintBoutonDescendre: '',
        HintCopier: '',
        HintBoutonParametre: '',
        TitreExportCSV: '',
        PersonnaliserListe: '',
        ChangerRang: '',
        EchangerRang: '',
        Rechercher: '',
        Filtrer: '',
        FiltrerActif: '',
        BtnAction: '',
        ElementSelectionne_D: '',
        ElementsSelectionnes_D: '',
        ReinitialiserFiltre: '',
        wai: {
          ModifierCoche: '',
          WAI_Tri_D: '',
          TrierColonne: '',
          Lu: '',
          Edition: '',
          NouvelElement: '',
          MsgRechercheNonTrouve: '',
          MsgRechercheNonTrouvePour_S: '',
          MsgRechercheXTrouveesPour_DDS: '',
          MsgRechercheXTrouveePour_DDS: '',
          CocherLigne: '',
          DecocherLigne: '',
          treegrid: '',
          tree: '',
          toolbar: '',
        },
      },
    );
    exports.TradGlossaireListe = TradGlossaireListe;
  },
  fn: 'glossaireliste.js',
});