IE.fModule({
  f: function (exports, require, module, global) {
    'use strict';
    Object.defineProperty(exports, '__esModule', { value: true });
    exports.TradDoubleAuth = void 0;
    const ObjetTraduction_1 = require('ObjetTraduction');
    const TradDoubleAuth = ObjetTraduction_1.TraductionsModule.getModule(
      'DoubleAuth',
      {
        Retour: '',
        TitreValiderCodePIN: '',
        RenforcerSecurite: '',
        EnSavoirPlus: '',
        LegendeStrategie: '',
        LegendeStrategieCompte: '',
        StrategieFort: '',
        StrategieMoyen: '',
        StrategieAucun: '',
        LegendeChoixStratTitre: '',
        LegendeChoixStratPIN: '',
        LegendeChoixStratNotif: '',
        MonCodePIN: '',
        PremierPIN: '',
        ConfirmPIN: '',
        CodeRecuPIN: '',
        NouveauCodePIN: '',
        MessageCreationCodePIN: '',
        EnregistrerSousNom: '',
        NbCaracteresMax_D: '',
        WAI_SaisiePINEtValider_D: '',
        WAI_SaisiePIN_D: '',
        WAI_ConfirmPINEtValider: '',
        WAI_ConfirmPIN: '',
        WAI_CodeReinitValide: '',
        WAI_MonCodeValide: '',
        Effacer: '',
        InfoSaisiePIN: '',
        Suivant: '',
        Annuler: '',
        PersonnesConfiance: '',
        NouvelAppareilRenseignerPIN: '',
        ProcedureReInitialisationCodePIN_S: '',
        WAI_ProcedureReInitialisationCodePIN_DS: '',
        WAI_ControleCodePINCourant: '',
        WAI_ControleCodePINCourantFixe: '',
        TitreReInitialisationCodePIN: '',
        ReinitialiserMonCodePIN: '',
        HintReinitialiserMonCodePIN: '',
        EMailReinitialisationPIN_S: '',
        NouvelAppareilOubliPIN: '',
        NouvelAppareilTentatives: '',
        ValiderTitreInconnu: '',
        ValiderInfoPIN: '',
        ValiderCodeValide: '',
        ValiderCodePinInvalide: '',
        Details: '',
        Client: '',
        Mobile: '',
        Navigateur: '',
        EnregistrerAppareilTitre: '',
        EnregistrerAppareilInfoIdentification: '',
        EnregistrerAppareilRappelNotif: '',
        EnregistrerAppareilSuggestions: '',
        EnregistrerAppareilNommerAppareil: '',
        EnregistrerAppareilResterInconnu: '',
        EnregistrerAppareilNomDejaUtilise: '',
        LibelleAppareilDejaUtilise: '',
        EnregistrerAppareilNomInvalide: '',
        Message_SourceConnexion_1: '',
        Message_SourceConnexion_2: '',
        Message_SourceConnexion_3_S: '',
        Message_SourceConnexion_4: '',
        FAQEnregistrement: '',
        LienFAQPIN: '',
        LienFAQEnregistrement: '',
        TitreFiche: '',
        PinInsuffisant: '',
        PinNonConfirme: '',
        PrefListeLibelle: '',
        PrefListeAppareil: '',
        PrefListeDate: '',
        PrefListeIcone: '',
        PrefChoisirDEnregistrer: '',
        PrefPensezASupprimer: '',
        PrefConfirmerSupprimer: '',
        AucunAppareilEnregistre: '',
        RenforcerSecuTitre: '',
        RenforcerSecuDefinirPIN: '',
        RenforcerSecuInfoPIN: '',
        RenforcerButtonModifier: '',
        AppareilsIdentifies: '',
        SecuriteRenforcee: '',
      },
    );
    exports.TradDoubleAuth = TradDoubleAuth;
  },
  fn: 'traductionsdoubleauth.js',
});