name: Datamining

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./src
        run: npm install

      - name: Clone pronote-datamining into src
        run: |
          git clone https://github.com/raphckrman/pronote-datamining.git src/pronote-datamining

      - name: Run Datamining Script
        working-directory: ./src
        env:
          PAT: ${{ secrets.PAT }}
          INSTANCE: ${{ secrets.INSTANCE }}
        run: node index.js
