name: Datamining

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./src
        run: npm install

      - name: Run Datamining Script
        working-directory: ./src
        env:
          INSTANCE: ${{ secrets.INSTANCE }}
        run: node index.js

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get current commit informations
        run: |
          COMMIT_ID=$(git rev-parse --short HEAD)
          DATE=$(date '+%d %B %Y')  
          echo "COMMIT_ID=$COMMIT_ID" >> $GITHUB_ENV
          echo "DATE=$DATE" >> $GITHUB_ENV

      - name: Commit & Push Changes
        run: |
          git add .
          if ! git diff-index --quiet HEAD; then
            git commit -m "${{ env.DATE }} - Build ${{ env.COMMIT_ID }}"
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
          fi